create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric not null check (price > 0),
  status text not null check (status in ('available', 'preorder')),
  image text,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists featured boolean not null default false;

alter table public.products enable row level security;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

notify pgrst, 'reload schema';