import postgres from "postgres";
import { products as seedProducts, type ProductItem, type ProductStatus } from "@/components/Product/products";

const API_URL = "https://dummyjson.com/products?limit=100";

const categoryNames: Record<string, string> = {
  beauty: "منتج عناية وجمال",
  fragrances: "عطر سعودي",
  furniture: "قطعة منزلية",
  groceries: "منتج غذائي",
  "home-decoration": "ديكور منزلي",
  tops: "زي أنيق",
  automotive: "منتج سيارات",
  motorcycle: "ملحق دراجات",
  laptops: "جهاز إلكتروني",
  smartphones: "هاتف ذكي",
  tablets: "جهاز لوحي",
  "mens-shirts": "ملابس رجالية",
  "mens-shoes": "حذاء رجالي",
  "mens-watches": "ساعة رجالية",
  "womens-dresses": "ملابس نسائية",
  "womens-shoes": "حذاء نسائي",
  "womens-watches": "ساعة نسائية",
  "womens-bags": "حقيبة نسائية",
  sunglasses: "نظارة شمسية",
  "skin-care": "عناية بالبشرة",
  "kitchen-accessories": "أدوات مطبخ",
};

type DummyProduct = {
  id: number;
  price: number;
  thumbnail: string;
  category: string;
};

function getPostgres() {
  const connectionString =
    process.env.POSTGRES_URL ||
    process.env.POSTGRES_PRISMA_URL ||
    process.env.POSTGRES_URL_NON_POOLING;

  return connectionString ? postgres(connectionString, { prepare: false }) : null;
}

async function ensureProductsTable() {
  const sql = getPostgres();
  if (!sql) return;

  await sql`
    create table if not exists public.products (
      id bigint generated by default as identity primary key,
      name text not null,
      description text not null,
      price numeric not null check (price > 0),
      status text not null check (status in ('available', 'preorder')),
      image text,
      created_at timestamptz not null default now()
    )
  `;
  await sql.end({ timeout: 2 });
}

export function hasPersistentStorage() {
  return Boolean(process.env.POSTGRES_URL || process.env.POSTGRES_PRISMA_URL || process.env.POSTGRES_URL_NON_POOLING);
}

export async function getCustomProducts(): Promise<ProductItem[]> {
  const sql = getPostgres();
  if (!sql) return [];

  await ensureProductsTable();
  const rows = await sql<ProductItem[]>`
    select id, name, description, price, status, image
    from public.products
    order by created_at desc
  `;
  await sql.end({ timeout: 2 });
  return rows;
}

export async function addCustomProduct(product: Omit<ProductItem, "id">) {
  const sql = getPostgres();
  if (!sql) throw new Error("أضف POSTGRES_URL في إعدادات Vercel");

  await ensureProductsTable();
  const [row] = await sql<ProductItem[]>`
    insert into public.products ${sql(product)}
    returning id, name, description, price, status, image
  `;
  await sql.end({ timeout: 2 });
  return row;
}

export async function updateCustomProduct(id: number, product: Omit<ProductItem, "id">) {
  const sql = getPostgres();
  if (!sql) throw new Error("أضف POSTGRES_URL في إعدادات Vercel");

  await ensureProductsTable();
  const [row] = await sql<ProductItem[]>`
    update public.products
    set name = ${product.name}, description = ${product.description}, price = ${product.price},
        status = ${product.status}, image = ${product.image || null}
    where id = ${id}
    returning id, name, description, price, status, image
  `;
  await sql.end({ timeout: 2 });
  if (!row) throw new Error("المنتج غير موجود");
  return row;
}

export async function deleteCustomProduct(id: number) {
  const sql = getPostgres();
  if (!sql) throw new Error("أضف POSTGRES_URL في إعدادات Vercel");

  await ensureProductsTable();
  await sql`delete from public.products where id = ${id}`;
  await sql.end({ timeout: 2 });
}

async function getRemoteProducts(): Promise<ProductItem[]> {
  const response = await fetch(API_URL, { next: { revalidate: 3600 } });
  if (!response.ok) throw new Error("Remote products unavailable");

  const data = await response.json() as { products: DummyProduct[] };
  return data.products.map((product) => ({
    id: product.id,
    name: `${categoryNames[product.category] || "منتج سعودي"} ${product.id}`,
    description: "منتج مختار بعناية بجودة عالية، متاح للطلب والتوصيل حتى باب البيت.",
    price: Math.round(product.price * 50),
    image: product.thumbnail,
    status: product.id % 5 === 0 ? "preorder" : "available",
  }));
}

export async function getAllProducts(): Promise<ProductItem[]> {
  const [remoteProducts, customProducts] = await Promise.all([
    getRemoteProducts().catch(() => seedProducts),
    getCustomProducts(),
  ]);

  return [...customProducts, ...remoteProducts];
}

export function isValidProductStatus(status: unknown): status is ProductStatus {
  return status === "available" || status === "preorder";
}
